import libs = enum_set%lib{enum_set} doctest%lib{doctest}

./: exe{run_tests} magic/

cxx.poptions =+ "-I$src_root/include"

exe{run_tests}: cxx{*} hxx{include/*} $libs

exe{*}: test = true

test.target = $cxx.target
